#!/bin/bash

if [ -d "./build" ]; then
	rm -rf ./build
fi 

FC=`which gfortran`

echo $FC


mkdir build
pushd build
cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_Fortran_COMPILER=$FC ..
make
popd

cp build/*.so .
